parameters:
    collects:
        Aws_UnHealthyHostCount:
            requestor_class: Monolist\Bundle\WatcherBundle\Model\Requestor\AwsUnHealthyHostCount
            identifier:
                - f
                - s
                - t
                - releasecandidate