_monolist_watcher:
    resource: "@MonolistWatcherBundle/Resources/config/routing.yml"

#monolist_watcher:
#    resource: "@MonolistWatcherBundle/Resources/config/routing.yml"
#    prefix:   /monolist

