UnHealthyHostCount:
    requestor_class: \CloudWatch\Metrics\SingleMetric\Requestor\UnHealthyHostCountRequestor
    entity_class: \Monolist\Bundle\WatcherBundle\Entity\CloudWatch\CloudWatchUnHealthyHostCount
    identifier:
        - f
        - s
        - t
        - releasecandidate