MyCustomReportGroupName:
    - CloudWatchLatency #full metric name (serviceName + metricName)
    - CloudWatchUnHealthyHostCount
    - CloudWatchUnHealthyHostCount

MyOtherReportGroupName:
    - CloudWatchUnHealthyHostCount #full metric name (serviceName + metricName)
    - CloudWatchUnHealthyHostCount
    - CloudWatchUnHealthyHostCount